name: Test-image-api
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
