name: TFL Camera Feed
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for TfL camera images
    defaultValue: tfl-cameras
    required: true
  - name: tfl_api_key
    inputType: Secret
    description: 'Your TfL API key'
    defaultValue: tfl_api_key
  - name: sleep_interval
    inputType: FreeText
    description: ''
    defaultValue: 60
    required: true
  - name: fence_coordinates
    inputType: FreeText
    description: 'Geofence coordinates. e.g. [(LAT1,LON1),(LAT2,LON2),(LAT3,LON3)]'
    defaultValue: ''
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py