name: temp
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: output-topic
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
