name: S3
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Input topic
    defaultValue: image-processed
    required: true
  - name: batch_time_interval
    inputType: FreeText
    description: Time interval in seconds to save data to S3 (set -1 to disable batching based on time)
    defaultValue: 3600
    required: false
  - name: batch_msg_count
    inputType: FreeText
    description: Message count in the batch (0 saves data as they arrive, -1 disables batching based on message count)
    defaultValue: 0
    required: false
  - name: parameters
    inputType: FreeText
    description: Comma separated list of parameters to look for in the received data
    defaultValue: ''
    required: true
  - name: aws_access_key_id
    inputType: HiddenText
    description: AWS S3 access key id
    defaultValue: xxx
    required: false
  - name: aws_access_key
    inputType: HiddenText
    description: AWS S3 access key
    defaultValue: xxx
    required: false
  - name: s3_bucket
    inputType: FreeText
    description: AWS S3 bucket name
    defaultValue: steve-demo-quix
    required: true
  - name: prefix
    inputType: FreeText
    description: File name prefix
    defaultValue: demo_
    required: false
  - name: s3_folder
    inputType: FreeText
    description: Name of the S3 folder to save to
    defaultValue: computer_vision_demo
    required: false
  - name: s3_folder_per_stream
    inputType: FreeText
    description: Flag to save different streams to different S3 folders.
    defaultValue: false
    required: false
  - name: suffix
    inputType: FreeText
    description: File suffix (e.g. file type extension)
    defaultValue: .csv
    required: false
  - name: timezone
    inputType: FreeText
    description: Timezone from the IANA Time Zone Database (e.g. Asia/Singapore) for orchestrating time-based batching and file naming.
    defaultValue: GMT
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
